[build]
  # No build command needed for static site
  publish = "src"
  
[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
