[build]
  # Set the source directory to the src folder
  publish = "src"
  
  # No build command needed since this is a static site
  # command = ""

[build.environment]
  # Set Node.js version if needed
  NODE_VERSION = "18"

# Redirect rules for clean URLs
[[redirects]]
  from = "/case-studies"
  to = "/case-studies/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301

# Handle client-side routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
